version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: audio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d audio_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: ./no_caps
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/audio_db
    restart: on-failure

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - backend
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/audio_db
    command: >
      sh -c "while ! pg_isready -h db -p 5432 -U user; do sleep 1; done; pytest"
volumes:
  postgres_data: