version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app

  worker:
    build: .
    command: celery -A main.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"